version: '3.8'

services:
  matchanalyzer-front-vuetify:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        environment: "raspy"
    container_name: "matchanalyzer-front-vuetify"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./dist:/var/www/html
    networks:
      - ma_backend
networks:
  ma_backend:
    external: true
